### ISSUE TITLE
Cannot read property 'assets' of undefined - Install Failed [Bug]

### ISSUE THREAD

**Issue by AstroEngineeer** [BetterDiscord/Installer#174]
****
This is the error I'm getting when installing 
----------------------------------------------------------------------------
Starting Install...

Creating required directories...
✅ Directory exists: C:\Users\Vicky\AppData\Roaming\BetterDiscord
✅ Directory exists: C:\Users\Vicky\AppData\Roaming\BetterDiscord\data
✅ Directory exists: C:\Users\Vicky\AppData\Roaming\BetterDiscord\themes
✅ Directory exists: C:\Users\Vicky\AppData\Roaming\BetterDiscord\plugins
✅ Directories created

Downloading asar file
❌ Failed to download package https://api.github.com/repos/rauenzi/BetterDiscordApp/releases
❌ Cannot read property 'assets' of undefined

The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd
-----------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/58505455/125038109-a3182080-e0b2-11eb-8772-b17eb8ccf0c7.png)

**Comment by zerebos** [comment]
GitHub picked a good time for the API to freak out. There is a workaround posted in our Discord servers. I will try to get a semi-permanent workaround up here ASAP.

**Comment by zerebos** [comment]
This is fixed with the latest hotfix release https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-hotfix

**Comment by AstroEngineeer** [comment]
Thanks

**Comment by zx18018** [comment]
The problem still present.
I download new honfix, but error the same
![image](https://user-images.githubusercontent.com/53554340/125914875-0be6357a-35d5-49df-a4d1-d44e9803f221.png)

**Comment by tropicaaal** [comment]
> The problem still present.
> I download new honfix, but error the same
> ![image](https://user-images.githubusercontent.com/53554340/125914875-0be6357a-35d5-49df-a4d1-d44e9803f221.png)

This is not the same issue. Check your firewall and antivirus.
