### ISSUE TITLE
Cant find Themes.

### ISSUE THREAD

**Issue by XXR34P3RXX** [BetterDiscord/Installer#37]
It wont show where to put themes or anything...
I tried repairing it but still does not work.
Lil bit of help.

**Comment by Jeolou** [comment]
in my case I can find the themes but It doesnt work

**Comment by XXR34P3RXX** [comment]
Fixed it im just dumb.

**Comment by EndZakuro** [comment]
Firstly, my themes doesn't work. After repair it, my themes gone away. But they still exist in my directory file
